# 1. Nispeten kolay

**Bir transaction oluştur, Shaun the Sheep'i Doctor Who olarak ekle, ardından bunu commit ya da rollback et**

**Shaun the Sheep**i **tblDoctor** tablosunda Doctor Who'nun 13 numarası olarak eklemek için bir sorgu yaz, ancak önce bir transaction başlat: 

<img src = "https://i.hizliresim.com/m1s929j.png">

Bu sorguyu (henüz çalıştırmadan) şu şekilde genişlet: 

* 2 + 2 = 4 olup olmadığını görmek için testler;
* Bu doğruysa işlemi geri alır; veya
* Bu yanlışsa commit eder.

**IF ... ELSE ...** syntaxını kullan.

Son olarak, tüm doktorların bir listesini görüntüle (**tblDoctor** tablosundaki satırlar). Şimdi sorgunu çalıştır -orijinal 12 doktoru göstermelidir (**Shaun the Sheep** eklenmemiştir).

2 + 2 = 5 olup olmadığını test etmek için sorgunu değiştir ve yeniden çalıştır. Şimdi yeni doktorunu almalısın: 

<img src = "https://i.hizliresim.com/jak93ze.png">

* Transaction gerçekleştirilmiştir ve yeni doktor listede görünür. 

Bu eklenen satırı manuel olarak sil, ardından (isteğe bağlı olarak) bu sorguyu **Baad example.sql** olarak kaydet ve kapat.

### Baad example.sql

<img src = "https://i.hizliresim.com/q7gk187.png">

<img src = "https://i.hizliresim.com/4e1pg4f.png">

<img src = "https://i.hizliresim.com/104fsnz.png">

# 2. Ortalama zorluk

**Sana ait olmayan tüm ülkeleri güncellemek için bir transaction oluştur, ardından rollback yap**

**CountryName** kolonunu evin olarak adlandırdığın ülkenin yanındaki (**My Country**) kelimelerini içerecek şekilde ayarlamak için **tblCountry** tablosunda bir **UPDATE** ifadesi kullan.

<img src = "https://i.hizliresim.com/lf30egb.png">

Şimdi bir transactiondaki diğer ülkelere (**Holiday destination**) eklemek için kodu değiştir. Update ifadesini çalıştırdıktan sonra:

* 1 + 1 = 2 ise transaction'ı rollback et; veya
* diğer türlü commit et

Bu sorguyu çalıştırdığında hiçbir şey değişmemelidir: 

<img src = "https://i.hizliresim.com/b7swklz.png">

* Ülkeni hariç tutarken, değiştirilen adı hesaba katmak için joker karakterler kullanmayı unutma!

1 + 1 = 3 olup olmadığını test etmek için koşulu değiştir ve yeniden çalıştır. Fazladan metnin eklenip eklenmediğini kontrol et: 

<img src = "https://i.hizliresim.com/ltr01ms.png">

* Yapacak daha iyi bir işin yoksa, gittiğin ülkeler için **Holiday**i **Visited** olarak değiştir.

Son olarak, biraz temizlik yapmak için lütfen bu sorguyu çalıştırarak ülke adlarını sıfırla: 

<img src = "https://i.hizliresim.com/4zt8ets.png">

Kendi ülkenin adını manuel olarak eski görkemine geri döndürebilseydin, bu çok iyi olurdu! teşekkür ederim...

İsteğe bağlı olarak bunu, **Stake your claims.sql** olarak kaydet ve ardından kapat.

### Stake your claims.sql

<img src = "https://i.hizliresim.com/a50g3pv.png">

<img src = "https://i.hizliresim.com/q0xaze7.png">

<img src = "https://i.hizliresim.com/hmegbza.png">

# 3. Ortalama Zorluk

**Aynı olayın birden çok kez eklenmesini önleyen bir transaction oluştur**

Doğum tarihini **Eventdate** kolonu ve **EventDetails** kolonu için uygun bir kayıt olacak şekilde **EventName**'ine *My DOB* yazarak yeni bir olay eklemek için bir insert statementi yaz:

<img src = "https://i.hizliresim.com/orlr0xf.png">

* **INSERT INTO tblEvent** ve **VALUES**i hatırla.

Artık bu insertü bir transactiona dönüştürebiliriz - ama önce **My DOB** gibi bir **Eventname** olan tüm olayları kaldırmak için bir delete komutu yaz.

<img src = "https://i.hizliresim.com/3z9vxv3.png">

**My DOB** adlı bir **Eventname**in zaten var olup olmadığını test eden, yoksa ekleyerek ve varsa bir mesaj veren bir transaction oluştur: 

<img src = "https://i.hizliresim.com/fwn53wt.png">

* Komut dosyasını birinci ve ikinci kez çalıştırmanın sonuçları. **EventID**'n farklı olacak!

İsteğe bağlı olarak bunu **Adding dates of import.sql** olarak kaydet ve ardından kapat.

### Adding dates of import.sql

<img src = "https://i.hizliresim.com/alvrxfj.png">

# 4. Ortalama zorluk

**Bir transactiondaki Dr Who düşmanlarının sayısını güncelle ve bunu commit ya da rollback et**

**tblEpisode** tablosunda **NumberEnemies** adlı yeni bir kolon oluşturmak için aşağıdaki scripti yaz ve çalıştır: 

<img src = "https://i.hizliresim.com/qy0oeu9.png">

Bu kolonu her bölüm için (ancak bir transaction içinde) düşman sayısına eşit olacak şekilde ayarlayacak bir update sorgusu yaz, ardından: 

* 100'den fazla satır etkilenirse (aşağıda gösterildiği gibi uygun bir mesaj görüntüleyerek) bu işlemi rollback et; ya da
* Commit et ve yeni doldurulan alan da dahil olmak üzere tüm bölümlerin bir listesini göster.

Kaç satırın etkilendiğini görmek için **<code>@@RowCount</code>** kullan, ancak değerinin üzerine yazılmaması için güncellemeyi çalıştırdıktan hemen sonra bunu bir değişkende saklamayı unutma.

Update sorgusunun syntaxının edepsiz olduğunu unutma: 

<img src = "https://i.hizliresim.com/tn06ayy.png">

Bu sorguyu çalıştırdığında, şöyle bir şey görmelisin: 

<img src = "https://i.hizliresim.com/3pnfjon.png">

* 117 satır güncellendiğinden, transaction rollback edilmelidir.

Şimdi sorgudaki eşiği 100'den 120'ye değiştir ve yeniden çalıştır. Bu sefer sorgu kolonu güncellemeli ve sonuçları göstermelidir: 

<img src = "https://i.hizliresim.com/plkw9x3.png">

* Birden fazla düşman elde etmek için episode id 15 olana kadar beklemen gerekir (bu noktada 3 aynı anda gelir).

Bunu çalıştırdığında, isteğe bağlı olarak sorgunu **Counting your friends.sql** olarak kaydet ve ardından kapat.

### Counting your friends.sql

<img src = "https://i.hizliresim.com/jk6h2c5.png">

<img src = "https://i.hizliresim.com/ot2nnbw.png">

# 5. Ortalama zorluk

**Insert, Update ve Delete komutlarını tek bir transaction'da kullan**

Önce **Westeros**'un değerini bir değişkende sakla. Şimdi bu değişkenin değerini **ContinentName** alanına eklemek için bir insert ifadesi yaz:

<img src = "https://i.hizliresim.com/ibhwb00.png">

Bunu yapmak için, önce **SET IDENTITY_INSERT tblContinent ON** komutunu çalıştırarak SQL Server'ın **ContinentId** identity kolonunun üzerine yazmasını sağlaman gerektiğini unutma. Sorgunun sonunda bu özelliği kapatmayı unutma.

**Insert** ifadesini çalıştırdıktan sonra, yorumla ancak değişkeni bırak.

<img src = "https://i.hizliresim.com/2scqkvg.png">

* Artık kıta isimlerini seçtiğinde **Westeros**'un listede göründüğünü görmelisin. Soru şu: En ölümcül kıta hangisi?

Bu syntaxı kullanarak değişkende tutulan kıtayı silmek için bir **TRANSACTION** başlat:

<img src = "https://i.hizliresim.com/n2sfwl1.png">

* Adının ilk harfi değişkenin ilk harfine (**W**) eşit değilse (**<>**), işlemi geri al: 

<img src = "https://i.hizliresim.com/o7u4gmh.png">

* Bu durumda, **You have died** mesajını göster ve **Westeros**'un kıta adını **Seven Kingdoms** olarak güncelle, ardından tüm kıtaları seç.

**You have won** göstermek ve ardından tüm kıtaları seçmek için **ELSE** koşulunu ayarla. 

Sonuç şimdi adına bağlı olacak. **W** ise, kıta görmezsin: 

<img src = "https://i.hizliresim.com/3sgm4mm.png">

* Hayatta kaldın ve Westeros'un yedi krallığı gitti. Danny gurur duyardı!

Bizden daha az şanslı olanlar için ölmüş olacaksın. **<>** öğesini bir **=** olarak değiştir ve scripti yeniden çalıştır. Bu sefer **Seven Kingdoms** ve daha mutlu bir mesaj görmelisin.

<img src = "https://i.hizliresim.com/giq2zdj.png">

İsteğe bağlı olarak **Game Of Thrones.sql** olarak kaydet ve kapat.

### Game Of Thrones.sql

<img src = "https://i.hizliresim.com/9xikueg.png">

# Archived - 1 - Ortalamadan daha zor

**Bir transaction'da, katıldığın kurs sayısını göstermek için bir kolono güncelle, ardından 5 veya daha az kursa katılanları sil - ardından rollback yap**

**tblPerson** tablosuna **Importance** adlı yeni bir tamsayı kolonu ekle: 

<img src = "https://i.hizliresim.com/bqiyxss.png">

Bir transaction başlatan ve ardından her kişi için **Importance** kolonunun değerini şu şekilde güncelleyen bir sorgu yaz: 

* Bu kişi 1 veya daha az kursa katılmışsa 10 (yani, bu **PersonId** için **tblDelegate** tablosundaki satır sayısı 1'den küçük veya ona eşitse)
* Bu kişi 2 ila 4 kursa katılmışsa 20; veya
* Aksi takdirde 30

Bu sorguyu tüm "unimportant" kişileri (yani önemi 10 olanlar) silecek ve kaç satırın silindiğini belirten bir mesaj yazdıracak şekilde genişlet: 

<img src = "https://i.hizliresim.com/epyt3to.png">

* 274 kişinin mimlendiğini görmelisin.

Son olarak, aşağıdakileri sağlayan bir koşul ekle:

* Tabloda hala en az 500 kişi kalmışsa transactionı commit et; ya da
* Aksi takdirde rollbackle

İsteğe bağlı olarak, bu sorguyu **How not run a training company.sql** olarak kaydet ve ardından kapat.

### How not run a training company.sql

<img src = "https://i.hizliresim.com/il09ydj.png">